apiVersion: v1
kind: ConfigMap
metadata:
  name: aws-auth
  namespace: kube-system
data:
  mapUsers: |
%{ for user in admin_users ~}
    - userarn: arn:aws:iam::${account_id}:user/${user}
      username: ${user}
      groups:
        - system:masters
%{ endfor ~}
